<?php

declare(strict_types=1);

namespace StoreStackCheckoutForWooCommerce;

defined('ABSPATH') || exit;


class Checkout
{
    /**
     * Stylesheet handle to which dynamic CSS is attached.
     *
     * @var string
     */
    public const STYLE_HANDLE = 'storestack-checkout';

    public function __construct()
    {
        add_filter('template_include', [$this, 'override_checkout_template'], 9999);
        add_action('wp_enqueue_scripts', [$this, 'checkout_enqueue_scripts'], 9999);
    }

    private function is_checkout_page(): bool
    {
        // Check if the current page is the WooCommerce checkout page, but not the "Order Received" (Thank You) or "Pay" endpoints.
        if (!is_checkout() || is_order_received_page() || is_checkout_pay_page()) {
            return false;
        }

        // Also check if the cart instance exists and is not empty
        if (!WC()->cart || WC()->cart->is_empty()) {
            return false;
        }

        return true;
    }

    public function override_checkout_template(string $template): string
    {
        if (! $this->is_checkout_page()) {
            return $template;
        }

        return SSCFW_PLUGIN_PATH . 'templates/checkout.php';
    }

    public function checkout_enqueue_scripts(): void
    {
        if (! $this->is_checkout_page()) {
            return;
        }

        // Remove theme-related CSS styles (plugin/gateway styles are preserved)
        $wp_styles = wp_styles();

        foreach ($wp_styles->queue as $handle) {
            if (!isset($wp_styles->registered[$handle])) {
                continue;
            }

            $src = $wp_styles->registered[$handle]->src;

            // 1. Check if the source file is located in the themes directory (this includes both parent and child themes)
            if (!empty($src) && str_contains($src, '/wp-content/themes/')) {
                wp_dequeue_style($handle);
            }

            // 2. Block themes: 'global-styles' is generated by WP core from theme.json / customizer
            if (in_array($handle, ['global-styles', 'wp-block-library-theme'], true)) {
                wp_dequeue_style($handle);
            }
        }

        // Dequeue WooCommerce Checkout Block styles and scripts
        wp_dequeue_script('wc-checkout-block');

        // Ensure the classic checkout scripts load so AJAX cart calculation
        // and third-party payment gateways still function correctly.
        wp_enqueue_script('wc-checkout');

        // Enqueue our CSS styles
        wp_enqueue_style(self::STYLE_HANDLE, SSCFW_PLUGIN_URL . 'assets/css/frontend.css', [], SSCFW_PLUGIN_VERSION);

        /** 
         * Fires after the checkout scripts are enqueued.
         * 
         * Allows developers to enqueue additional scripts or styles for the checkout page.
         * 
         * @since 1.0.0
         */
        do_action('storestack_checkout_enqueue_scripts');
    }
}
